### PR TITLE
Add a short command to start the public UI for development, and update README.md

### PR DESCRIPTION
**Pull request by asokoloski**
Without this, I'm surely going to forget to set the environment variable to connect to my local pgc-api instead of the remote one.  Again :)

### CODE REVIEW

**Comment by boralben** [comment]
@asokoloski thank you for suggesting this. My understanding is that node projects define their various scripts in the `scripts` section of the `package.json` so that they can be invoked with `npm run <script name>`. What do you think about moving the definition of the existing scripts to `run.sh` and using the `npm run` command as an alias for invoking `run.sh`?

I'm suggesting this in order to retain the traditional npm way of enumerating a project's scripts while recognizing that `run.sh` will be nice for encapsulating the script definitions and keeping the `package.json` uncluttered in the case of more complicated scripts.

As a side note, I'd suggest naming this `local` or `dev`.

Ex.
```
"scripts": {
    "start": "./run.sh start",
+   "local": "./run.sh local",
...
}
```
Usage: `npm run local`

**Comment by asokoloski** [comment]
@boralben Great idea about using npm run, I'll change it.

On the point of `local` and `start` -- from my point of view, running against the local server is more common, which is why I gave it the sort of "default" command `start`.  But I understand that may not be true for everyone.  Do you feel like doing it this way is preferable to something like `start` for the local server, and `prod` (or `start-prod` or something) to run against the production API?

(I don't feel strongly about it at all, just thought I'd ask)

**Comment by asokoloski** [comment]
Oh, thinking about it now, I'd be changing behavior that everyone is used to.  Yeah, never mind, I'll just use `local` and `start` like you suggested :)

**Review by boralben — APPROVED** [review]
🎉

**Pull request merged**
